# Minecraft 26.2 Target
minecraft_version=26.2
loader_version=0.16.10
fabric_version=0.152.1+26.2

mod_version=1.3.1+26.2
maven_group=com.dasik.mcagenderbridge
archives_base_name=mca-female-gender-bridge

org.gradle.java.home=E:/JDK25
fabric.loom.suppressJavaCompatibilityChecks=true
loom.suppressJavaCompatibilityChecks=true
